apiVersion: apps/v1
kind: Deployment
metadata:
  name: acraks-deployment
spec:
  replicas: 1
  selector:
   matchLabels:
      app: acraks
  template:
    metadata:
      labels:
        app: acraks
    spec:
      containers:
      - name: acraks
        image: parthakundu1973/acraks:latest
        ports:
         - containerPort: 80
